name: validate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "the environment to validate"
        required: true
        default: "staging"
        type: choice
        options:
          - PROD
          - STAGING
  workflow_call:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        default: "STAGING"
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run integration tests
        run: cargo test --test integration
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}

          # Run validate swift
      - name: Run validate swift
        uses: ./.github/workflows/validate_swift.yml
        with:
          notify-endpoint: ${{ inputs.environment == 'PROD' && 'cast.walletconnect.com' || 'staging.cast.walletconnect.com' }}
          relay-endpoint: ${{ inputs.environment == 'PROD' && 'relay.walletconnect.com' || 'staging.relay.walletconnect.com' }}
