name: validate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "the environment to validate"
        required: true
        default: "staging"
        type: choice
        options:
          - PROD
          - STAGING
  workflow_call:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        default: "STAGING"
        type: string

jobs:
  validate-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run integration tests
        run: cargo test --test integration
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          NOTIFY_PROJECT_SECRET: ${{ secrets.NOTIFY_PROJECT_SECRET }}

   